#这些是需要每个项目都独立写一个的
#-------------------
main_name=main
# ui_name=
# main_name=main
# ui_name=main_ui
sys=linux


#后面就是不用独立修改的
#-------------------
ifeq ($(sys),win)
	py=python
# py=d:\pf\python34\python.exe
	uic=D:\pf\Python34\Lib\site-packages\PyQt4\uic\pyuic.py
	ui_editor=D:\pf\Python34\Lib\site-packages\PyQt4\designer.exe
	rm_bin=del
	packer=d:\pf_win10\python34\Scripts\cxfreeze
else
	py=python3
	uic=/usr/lib/python3/dist-packages/PyQt4/uic/pyuic.py
	ui_editor=designer
	rm_bin=rm
endif

source_file=$(main_name).py
# ifeq ($(strip($(ui_name))),)
# 	source_file=$(main_name).py
# else
# 	source_file=$(main_name).py  $(ui_file)
# endif

d debug : $(source_file)
	rxvt -e $(py) $(main_name).py &

r run : $(source_file)
	$(py) $(main_name).py

c	:
	$(rm_bin) __pycache__ -r
	$(rm_bin) *.pyc

# t	:
# 	$(py) replace_str.py $(ui_name).py

out:
	$(py) $(packer) $(main_name).py --base-name=Win32GUI

out2:
	$(py) setup.py bdist_msi --icon=$(main_name).ico
